name: Release image

on:
  push:
    tags:
      - "v[0-9]"

jobs:
  docker:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: gh-robot-reporter
          method: jwt
          secrets: |
            secret/data/robot-reporter DOCKERHUB_TOKEN
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ steps.secrets.outputs.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joonvena/robot-reporter:${{ github.ref_name}}